import {
  Box,
  Button,
  HStack,
  Heading,
  IconButton,
  Image,
  Modal,
  ModalBody,
  ModalCloseButton,
  ModalContent,
  ModalFooter,
  ModalHeader,
  ModalOverlay,
  Stack,
  Text,
  useDisclosure,
} from '@chakra-ui/react';
import React from 'react';
import { FaCopy, FaDownload, FaInfoCircle, FaLink } from 'react-icons/fa';
import { ImageObject } from '../Newtab';
import { useClipboard } from '@chakra-ui/react';

function AboutModal({ image }: { image: ImageObject }) {
  const { isOpen, onOpen, onClose } = useDisclosure();
  const { onCopy, hasCopied } = useClipboard(image.prompt);

  return (
    <>
      <HStack
        onClick={onOpen}
        _hover={{
          opacity: 1,
          cursor: 'pointer',
        }}
        opacity={0.8}
      >
        <IconButton
          icon={<FaInfoCircle />}
          aria-label="Download Wallpapers"
          size={'sm'}
        />
        <Text
          textAlign={'left'}
          userSelect={'none'}
          fontWeight={'bold'}
          fontSize={'xs'}
          textShadow={'0px 2px 6px rgba(0, 0, 0, 0.4)'}
        >
          Image Generated by AI
        </Text>
      </HStack>
      <Modal isOpen={isOpen} onClose={onClose}>
        <ModalOverlay />
        <ModalContent>
          <ModalHeader>About</ModalHeader>
          <ModalCloseButton />
          <ModalBody>
            <Stack gap={4}>
              <Stack>
                <Heading size={'sm'}>Did you know?</Heading>
                <Text>
                  Both the image and the quote you're seeing were generated
                  using Leap AI.
                </Text>
              </Stack>
              <Stack>
                <Heading size={'sm'}>Want more wallpapers?</Heading>
                <Text>
                  Browse the full gallery of current plus past Ambience
                  wallpapers.
                </Text>
                <Button
                  rightIcon={<FaLink />}
                  as="a"
                  target="_blank"
                  href={'https://wallpapers.fyi'}
                  download
                >
                  Browse All
                </Button>
              </Stack>
              <Stack>
                <Heading size={'sm'}>Image Prompt</Heading>
                <Text>
                  Below is the prompt that was used to generate this image.
                </Text>
                <Box bg={'whiteAlpha.200'} p={4} rounded={'md'}>
                  <Text>{image.prompt}</Text>
                </Box>
                <Button rightIcon={<FaCopy />} onClick={onCopy}>
                  {hasCopied ? 'Copied' : 'Copy'}
                </Button>
              </Stack>
              <Stack>
                <Heading size={'sm'}>Download Image</Heading>
                <Text>
                  Love this image? Download it to your computer by clicking the
                  button below.
                </Text>
                <Image src={image.imageUrl} rounded={'md'} />
                <Button
                  rightIcon={<FaDownload />}
                  as="a"
                  target="_blank"
                  href={image.imageUrl}
                  download
                >
                  Download
                </Button>
              </Stack>
            </Stack>
          </ModalBody>
          <ModalFooter></ModalFooter>
        </ModalContent>
      </Modal>
    </>
  );
}

export default AboutModal;
