import {
  Box,
  Heading,
  Modal,
  ModalBody,
  ModalCloseButton,
  ModalContent,
  ModalFooter,
  ModalHeader,
  ModalOverlay,
  Stack,
  Text,
  useDisclosure,
} from '@chakra-ui/react';
import React from 'react';
import { ImageObject } from '../Newtab';

function AboutModal({ image }: { image: ImageObject }) {
  const { isOpen, onOpen, onClose } = useDisclosure();
  return (
    <>
      <Text
        textAlign={'left'}
        userSelect={'none'}
        opacity={0.6}
        onClick={onOpen}
        _hover={{
          opacity: 1,
          cursor: 'pointer',
        }}
      >
        Image Generated by AI
      </Text>
      <Modal isOpen={isOpen} onClose={onClose}>
        <ModalOverlay />
        <ModalContent>
          <ModalHeader>About</ModalHeader>
          <ModalCloseButton />
          <ModalBody>
            <Stack gap={4}>
              <Stack>
                <Heading size={'sm'}>Did you know?</Heading>
                <Text>
                  Both the image and the quote you're seeing were generated by
                  AI
                </Text>
              </Stack>
              <Stack>
                <Heading size={'sm'}>Image Prompt</Heading>
                <Box bg={'blackAlpha.200'} p={4} rounded={'md'}>
                  <Text>{image.prompt}</Text>
                </Box>
              </Stack>
            </Stack>
          </ModalBody>
          <ModalFooter></ModalFooter>
        </ModalContent>
      </Modal>
    </>
  );
}

export default AboutModal;
