export const prompts = [
  "cosmic galaxy scene, depicting a breathtaking view of stars and planets; soft ambient lighting, hyperrealistic style, cool color palette, shot with a wide-angle lens",
  "vibrant geometric patterns, incorporating a mix of shapes and colors; high contrast lighting, minimalistic style, warm color palette, captured with a macro lens",
  "aerial view of lush, winding river cutting through a dense forest; natural sunlight, impressionistic style, deep earthy tones, photographed with a drone camera",
  "modern abstract painting, using bold brushstrokes and vivid colors; balanced diffused lighting, abstract expressionist style, bold complementary colors, created with a fisheye lens",
  "bird's-eye view of a mesmerizing coral reef, teeming with marine life; underwater lighting, documentary-inspired style, vibrant aquatic hues, taken with a waterproof camera",
  "intricate mandala design, a harmonious blend of colors and shapes; backlit illumination, spiritual and meditative style, bright and colorful palette, depicted through a tilt-shift lens",
  "futuristic city skyline, illuminated by neon lights and holograms; glowing artificial lights, cyberpunk style, electric color scheme, captured with a long exposure technique",
  "captivating aurora borealis, a natural light show in the polar sky; soft ambient glow, panoramic landscape style, shifting color gradients, photographed with a DSLR camera and a wide field of view",
  "flower field in full bloom, creating a breathtaking color palette; golden hour lighting, botanical illustration style, vibrant and varied floral colors, shot with a telephoto lens",
  "classic arcade game characters, designed in a pixel art style; directional 8-bit lighting, nostalgic retro style, primary color palette, rendered with a digital art program",
  "zen garden with raked sand patterns and carefully placed stones; serene natural light, Asian-inspired style, monochrome color scheme, captured with a shallow depth of field",
  "topographical map, showcasing the beauty of Earth's diverse landscapes; sunlit aerial view, cartographic style, subtle and earthy tones, digital rendering with a 3D camera",
  "origami-inspired art, transforming paper into intricate 3D shapes; strong spotlighting, contemporary art style, pastel color palette, shot with a precisely focused camera",
  "narrow alleyway in an urban city, covered with colorful graffiti; moody and dim lighting, street art style, vivid and chaotic color mix, photographed with a high ISO setting",
  "surreal floating islands, defying gravity against a dreamy sky; ethereal backlighting, fantasy-inspired style, rich and vibrant color harmony, created with a digital painting software",
  "silhouette of a tree against a gradient sky at twilight; low-key sunset light, minimalist style, peaceful and warm color progression, captured with a vintage film camera",
  "macro shot of a frosty leaf, showcasing intricate ice patterns; dramatic side-lighting, nature-inspired style, cool and crisp blues, shot with a high-resolution macro lens",
  "watercolor splash, blending together various hues and tones; diffuse natural light, impressionistic style, harmonious color blend, photographed with a high-speed camera",
  "magnificent waterfall cascading into a serene, crystal-clear pool; bright top-down lighting, scenic landscape style, vibrant greens and blues, captured with a slow shutter speed",
  "time-lapse of busy city traffic, creating streaks of vibrant light patterns; dynamic motion blur, urban exploration style, glowing neon palette, photographed with a tripod and stable camera settings",
  "cherry blossoms in full bloom, creating a pink floral canopy; soft-filtered sunlight, romantic and dreamy style, pale pink and white tones, captured with soft focus and bokeh effects",
  "dynamic neon geometric shapes on a contrasting black background; electric backlighting, futuristic design style, bold neon color palette, rendered with a computer-generated software",
  "majestic ice cave, illuminated by ethereal, glowing light; dramatic natural reflections, otherworldly style, icy blues and purples, taken with a high dynamic range (HDR) camera setting",
  "terraced rice fields, showcasing the beauty of human-made landscapes; rich, warm sidelight, aerial photography style, lush green tones, shot with a high-altitude drone camera",
  "vintage world map, a detailed representation of global exploration; soft, even lighting, antique cartography style, faded sepia color palette, photographed with a high-resolution scanner",
  "modern architectural marvel, showcasing curves and lines in harmony; striking sunbeams, futuristic minimalist style, bold monochromatic theme, captured with geometric composition techniques",
  "line art portrait, minimalist design with striking features; simple contrasting shadows, modern art style, black and white palette, created with a digital drawing tablet",
  "long exposure photography of a meteor shower, streaks of light across the sky; natural celestial illumination, astrophotography style, deep sky blues and starry whites, taken with a sensitive camera sensor",
  "gorgeous view of rolling hills, blanketed by a sea of fog; misty, diffused light, atmospheric landscape style, soothing green and gray tones, photographed with a high-quality panoramic lens",
  "bright and energetic color gradient, transitioning seamlessly from hue to hue; smooth, radiant light, digital art style, intense and bold color spectrum, designed with a graphic software program",
  "desert landscape under a starry night sky; gentle moonlight, artistic desert composition, warm earthy hues, captured with a wide-aperture lens",
  "tropical beach scene at sunrise, with swaying palm trees and white sands; warm golden light, idyllic vacation style, vivid sky and ocean tones, captured with a high-quality wide-angle lens",
  "CYMK color explosion; spotlit complementary colors, graphic design-inspired style, bright and bold, captured with a high shutter speed",
  "modern city skyline at dusk, featuring iconic buildings and reflections; twilight glow, architectural photography style, cool blues and rich orange hues, taken with a tripod and a long exposure setting",
  "ancient abandoned temple overtaken by nature; mystical sunlight filtering through, archaeological style, muted earth tones and greens, photographed with a lead-in lines composition technique",
  "vast mountain range, with peaks that pierce the sky; high-altitude sunlight, majestic landscape style, earthy colors, captured with a wide field of view and a panoramic lens",
  "whimsical carousel, with ornate and brightly painted horses; vividly colored lighting, nostalgic amusement park style, vibrant and playful color palette, shot with a motion blur effect",
  "cosmic nebula, swirling with vivid colors and sparkling stars; soft celestial glow, immersive space art style, deep blues and vibrant colors, created with digital art software",
  "glassblowing art, with molten glass being spun and shaped; red-hot backlighting, artisan craft style, fiery oranges and reds, photographed with a short exposure time",
  "iconic movie scene, recreated with explorative composition and lighting techniques; cinematic flair, transformative film style, engaging color combinations, taken with a lens that conveys depth and emotion",
  "roaring thunderstorm, with lightning streaking across the sky; powerful contrast, dramatic weather photography style, rich blues and electric whites, captured with a long exposure setting",
  "vibrant close-up of butterfly wings; delicate, diffused light, macro nature style, vivid colors and fine details, shot with a high-resolution macro lens",
  "stylized geometric street art, using bold lines and contrasting colors; vibrant, indirect light, urban graffiti style, eye-catching color combinations, photographed with a wide-angle lens",
  "sweeping treetops, showcasing a variety of fall foliage colors; soft, even light, nature-inspired style, bright yellows, oranges, and reds, taken with a bird's-eye perspective and a drone camera",
  "re-imagined iconic painting, using digital art techniques and tools; uniform, tinted light, contemporary interpretation style, harmonious colors, created with advanced drawing software",
  "impressive cave formation, with stalactites and stalagmites; dim and mystical lighting, geological style, natural earth tones, captured with a light-sensitive camera and a wide aperture setting",
  "colorful hot air balloons, floating among the clouds; bright, sunlit sky, whimsical adventure style, festive and bright hues, taken with a high-quality zoom lens",
  "famous landmark captured from an unusual angle; dramatic shadows, architectural photography style, contrasting colors, shot with fisheye lens",
  "enchanting forest stream, with sunlight piercing the canopy; soft, dappled light, fairytale-inspired style, lush greens and earthy tones, photographed with a wide aperture and a shallow depth of field",
  "microscopic view of crystalline structure; striking backlighting, scientific imagery style, vivid and intricate color patterns, taken with a high-resolution microscopic camera",
  "bold collage of hand-written typography; varied light sources, experimental and artistic style, contrasting and harmonious colors, created with mixed media and digital manipulation",
  "steampunk-inspired cityscape, with gears, cogs, and airships; moody, industrial lighting, alternate universe style, rich bronze and metallic hues, rendered with a digital art program",
  "pop art representation of a popular cultural icon; bold and flat lighting, daring and vibrant style, bright primary colors, created with vector illustration software",
  "calm and reflective lakeside scene, with still water and a mirror-like reflection; soft, cool light, tranquil landscape style, peaceful blues and neutral tones, captured with a high-resolution camera",
  "intricate papercut art, casting shadows on a white surface; sharp, angled lighting, minimalist artistic style, monochrome color palette, photographed with accurate depth perception",
  "captivating dance performance, with graceful movements and flowing fabric; warm stage lighting, fluid motion style, passion-filled colors, taken with a fast shutter speed and accurate focus",
  "icy and frost-covered tree branches; soft, cool light, winter wonderland style, crisp whites and blues, photographed with a shallow depth of field and focus on fine details",
  "dazzling fireworks display, filling the night sky; burst of brilliant colors, celebration-inspired style, vibrant and glowing hues, captured with a long exposure setting and a wide field of view",
  "fluid acrylic art, with swirling colors and mesmerizing patterns; even, diffuse light, liquid creativity style, rich and contrasting color combinations, captured with a high-resolution camera",
  "soft-focus color gradient, transitioning smoothly between hues and shades; calming ambient light, soothing abstract style, harmonious and relaxing colors, photographed with a soft-focus lens",
  "textural surface, showcasing intricate patterns and relief; directional sidelight, unique material style, deep shadows and highlights, taken with a macro lens for high detail",
  "multiplicity of metallic shades, reflecting a complex array of colors; varying light sources, alluring metalwork style, shimmering and muted tones, captured with a high-quality lens",
  "waves of sand dunes, creating abstract lines and shapes; low and warm sunlight, nature-inspired pattern style, golden hues and earthy tones, taken with a high-resolution camera",
  "close-up detail of interlaced fabric fibers; backlit lighting, textile-focused style, soft and muted colors, shot with a high-resolution macro lens",
  "splashes of vibrant paint, blending and merging on a canvas; saturated light, expressive abstract style, bold and intense hues, captured with a fast shutter speed",
  "moire pattern, an intriguing effect created by overlapping lines and grids; well-balanced lighting, optical illusion style, hypnotic black and white, photographed with accurate focus",
  "cracked earth patterns, illustrating natural texture and variety; top-down lighting, organic surface style, desaturated earth tones, taken with a high-resolution camera",
  "holographic foil, reflecting a rainbow of iridescent colors; angled light source, futuristic material style, prismatic and shifting hues, photographed with an ultra-sharp lens",
  "abstract representation of shattered glass; strong and contrasting highlights, fragmented style, cool crisp whites and blues, captured using high-resolution techniques",
  "translucent ice crystals, revealing intricate patterns and details; backlit, cold light, frozen art style, icy blues and whites, taken with a high-resolution macro lens",
  "smooth, undulating gradient, inspired by molten lava; vibrant backlighting, intense natural phenomenon style, blazing oranges and deep blacks, created with digital art tools",
  "enlarged view of carbon fiber weave; sharp, raking light, industrial material style, monochromatic shades of gray, photographed with a high-magnification macro lens",
  "abstract bubble patterns on a dark background; reflective, directed light, ephemeral and floating style, colorful and vibrant hues, taken with a fast shutter speed",
  "impressionistic brushstrokes, forming an abstract seascape; diffused, natural light, painterly style, varied shades of blues, greens, and grays, photographed with a high-resolution camera",
  "macro shot of rusted, weathered metal; dramatic, angled lighting, rugged surface style, rich oranges and muted tones, captured with a high-resolution macro lens",
  "rippling water surface, capturing sunlight reflections; glistening natural light, aqueous abstract style, shimmering blues and greens, taken with a high-quality lens",
  "futuristic light trails, formed by fast-moving particles; dynamic streaks of color, high-speed motion style, bright neon shades on a dark background, captured with long exposure photography",
  "marbled paper, combining swirling colors and unpredictable patterns; soft, even lighting, fluid art style, rich and harmonious tones, photographed with a high-resolution camera",
  "microscopic view of intricate crystal formations; dramatic backlighting, mineralogical art style, vivid and contrasting color patterns, taken with a high-resolution microscopic lens",
  "kaleidoscopic design, showcasing stunning symmetry and colorful geometry; vibrant radial light source, mesmerizing mandala style, bright and vivid hues, created with digital manipulation",
  "highly polished chrome surface, reflecting distorted shapes and light; contrasting highlights, metallic abstraction style, cool grays and whites, captured with accurate depth perception",
  "imposing sculptural texture formed by complex geometric shapes; calculated light source, contemporary art style, monochromatic palette, photographed with a wide-angle lens",
  "colorful dust explosion, mid-air, captured with a high-speed camera; dynamically suspended particles, momentary art style, vibrantly varied hues, taken with a fast shutter speed",
  "fluorescent liquid dye patterns, activating under UV light; electric ultraviolet radiance, futuristic fluid style, glowing and vivid neon colors, captured with a specialized UV-sensitive lens",
  "fierce inferno, with dancing flames and vibrant colors; dramatic side-lighting, untamed fire style, intense reds, oranges, and yellows, photographed with a fast shutter speed",
  "fine strands of illuminated fiber optics, intertwining and glimmering; focused light, technological abstraction style, dazzling spectrum of colors, taken with a high-quality lens",
  "elaborate fractal pattern, spiraling into endless complexity; perfect symmetry, mathematical art style, vibrant and intense hues, rendered with a computer-generated algorithm",
  "glazed ceramic surface, featuring iridescent colors and reflections; diffuse light, artisan pottery style, shifting and shimmering tones, photographed with a high-resolution camera",
  "serene mountain lake reflecting the surrounding peaks; soft morning light, tranquil landscape style, cool blues and earthy greens, captured with a wide-angle lens",
  "dynamic street scene with pedestrians bustling through a crosswalk; high contrast lighting, urban photography style, lively and colorful mix, taken with a freeze frame motion technique",
  "spiral staircase, creating a hypnotic pattern with converging lines; dramatic shadows, architectural design style, monochrome color palette, photographed from a bird's-eye view",
  "curled up fern frond, emphasizing symmetry and natural patterns; soft, diffused light, botanical art style, lush greens and earthy browns, shot with a macro lens",
  "handwritten script in elegant calligraphy, with ink and quill on parchment; warm, even lighting, vintage writing style, sepia-toned colors, captured with a high-resolution scanner",
  "expansive ocean surface with a minimal horizon line; atmospheric light, minimalist seascape style, soothing blues and soft whites, taken with a high-quality wide-angle lens",
  "diagonally stacked rows of vibrant rainbow-colored books; even, natural light, geometric bookshelf style, bold and bright hues, photographed with a low depth of field",
  "flower petals captured in extreme close-up, revealing intricate textures; backlit, contrasting light, macro botanical style, rich and vibrant colors, shot with a high-resolution macro lens",
  "intimate portrait of a single raindrop on a leaf; diffused, tender light, poetic nature style, vivid greens and clear refracted elements, taken with a macro lens and focused depth of field",
  "sunburst effect created by shards of reflective glass; radiant light, emerging radiance style, shimmering gold and warm tones, photographed with a wide aperture setting",
  "abandoned industrial warehouse with weathered surfaces and rusted machinery; dramatic directional light, urban decay style, muted grays and earth tones, captured with a gritty HDR technique",
  "starry night sky with a distinct constellation in focus; accurate celestial alignment, astrophotography style, dark blues and twinkling whites, shot with a long exposure and a sensitive camera sensor",
  "dense, mossy forest scene, with sunlight filtering through fog; ethereal atmosphere, enchanted woodland style, vibrant greens and soft light, photographed with a wide aperture and a shallow depth of field",
  "illuminated city skyline at twilight, with a body of water in the foreground; calming dusk light, urban reflection style, cool blues and magical purples, taken with a tripod and long exposure setting",
  "high-speed photography of a droplet splashing into still water; precise timing, fluid motion style, dynamic interaction of colors, captured with a fast shutter speed and a sharp lens",
  "intricate textile weaving, showcasing the harmony of colors and patterns; soft, even light, artisan fiber art style, rich and complementary hues, photographed with a high-resolution camera",
  "abstract swirls of molten lava; vivid, glowing light, volcanic phenomenon style, fiery reds and deep blacks, captured with a high-quality telephoto lens",
  "majestic desert landscape with a convoy of camels crossing sand dunes; warm setting sun, exotic adventure style, golden hues and long shadows, taken with a high-quality wide-angle lens",
  "rooftop view of a crowded cityscape, with a mix of architectural styles; expansive aerial perspective, architectural juxtaposition style, diverse and harmonious tones, captured with a drone camera",
  "silhouette of a ballet dancer leaping gracefully against a glowing backdrop; radiant stage light, expressive dance style, fluid motion and contrasting shapes, photographed with a high-speed camera",
  "crescent moon illuminating a peaceful ocean at night; tranquil lunar light, seascape abstraction style, deep blues and shimmering silvers, captured with long exposure and a sensitive camera sensor",
  "soft pastel chalk blending, creating a smooth gradient of colors; even, natural light, impressionist drawing style, calming and harmonious tones, photographed with a high-resolution camera",
  "patterns of sunlight dappling through a dense canopy of leaves; dappled, vibrant light, layered shade style, deep greens and golden specks, taken with a high-quality lens",
  "vividly dyed feathers, displaying an array of exotic colors and patterns; soft, directional light, avian art style, bold and striking hues, captured with an ultra-sharp macro lens",
  "entwined branches of a gnarled tree, creating a maze of intricate lines; high-contrast lighting, natural sculpture style, somber earth tones, photographed with a wide field of view and a vintage film camera",
  "dynamic perspective of a spiraling roller coaster, captured in motion; fluid movement, amusement park excitement style, vivid colors and sharp contrast, shot with a fast shutter speed and freeze-frame motion technique",
  "rustic countryside scene with wildflowers and a meandering stream; warm, golden light, pastoral landscape style, rich greens and vibrant blooms, photographed with a high-quality wide-angle lens",
  "vibrant paint splatters against a contrasting black background; artful chaos, expressive action style, vivid colors and spontaneous form, captured with high-speed photography",
  "sunset reflecting off mirrored glass skyscrapers; rich, glowing light, urban splendor style, warm golden tones and cool blues, taken with a high-quality camera and a wide field of view",
  "lasers illuminating an abstract geometric grid; pattern of light and shadow, cutting-edge tech style, electric blues and neon greens, captured with long exposure photography",
  "minimalist landscape of undulating dunes under a vast sky; soft, timeless light, desert abstraction style, sandy neutrals and pastel blues, taken with a high-quality panoramic lens",
  "bold contour lines of a facial profile against a solid color; striking shadows, modernist portrait style, black and white palette, created with a digital drawing program",
  "imposing cloud formation contrasting against a serene landscape; atmospheric light, awe-inspiring nature style, pale grays and earth tones, captured with a wide field of view and a deep depth of field",
  "tessellation of colorful tiles in a geometric design; even, natural light, intricate mosaic style, harmonious colors and precise patterns, photographed with a high-resolution camera",
  "monochromatic shadows and highlights on a smooth, curved surface; soft, reflective light, abstract form style, gradient tones, captured with an accurate depth of field",
  "underwater scene featuring a lively school of fish; dappled sunlight, marine exploration style, vibrant blues and aquatic hues, taken with a high-quality waterproof camera",
  "glowing bioluminescent creatures seen in a dark ocean depths; natural phosphorescence, deep-sea life style, luminescent blues and greens, captured with a low-light sensitive camera",
  "stylized musical notes intertwined with colorful ribbons; warm, radiant light, harmonious melody style, vibrant and playful colors, created with vector illustration software",
  "golden wheat field under a glowing sunset sky; soft backlighting, rural tranquility style, warm yellows and deepening sky tones, captured with a high-resolution camera",
  "intricate mesh of gears and cogs, revealing the inner workings of a machine; dramatic contrast, mechanical complexity style, metallic grays and bronze, photographed with a high-resolution camera",
  "patterned shadows cast by ornate wrought iron grating; intricate highlights and lowlights, artistic metalwork style, smooth grayscale tones, taken with a wide field of view and accurate focus",
  "inky, swirling clouds of pigment in water; dreamlike diffusion, liquid art style, merging colors and abstract shapes, captured with a high-speed camera",
  "maze-like view of a sprawling library, with towering shelves of books; warm, ambient light, bookworm's paradise style, rich earth tones and muted colors, photographed with a wide field of view",
  "textured view of an oil painting, revealing thick layers of paint and bold brushstrokes; directional sidelight, impasto technique style, vibrant and varied colors, shot with a macro lens",
  "wide view of a rock concert, with a sea of fans raising their hands in unison; vibrant stage lighting, energetic music style, colorful and ecstatic crowd, taken with a high-quality wide-angle lens",
  "delicate tracing of a spider web, covered in glistening dewdrops; soft, glowing light, enchanted nature style, shimmering translucent elements, captured with a macro lens and a shallow depth of field",
];
