export const prompts = [
  "cosmic galaxy scene, depicting a breathtaking view of stars and planets; soft ambient lighting, hyperrealistic style, cool color palette, shot with a wide-angle lens",
  "vibrant geometric patterns, incorporating a mix of shapes and colors; high contrast lighting, minimalistic style, warm color palette, captured with a macro lens",
  "aerial view of lush, winding river cutting through a dense forest; natural sunlight, impressionistic style, deep earthy tones, photographed with a drone camera",
  "modern abstract painting, using bold brushstrokes and vivid colors; balanced diffused lighting, abstract expressionist style, bold complementary colors, created with a fisheye lens",
  "bird's-eye view of a mesmerizing coral reef, teeming with marine life; underwater lighting, documentary-inspired style, vibrant aquatic hues, taken with a waterproof camera",
  "intricate mandala design, a harmonious blend of colors and shapes; backlit illumination, spiritual and meditative style, bright and colorful palette, depicted through a tilt-shift lens",
  "futuristic city skyline, illuminated by neon lights and holograms; glowing artificial lights, cyberpunk style, electric color scheme, captured with a long exposure technique",
  "captivating aurora borealis, a natural light show in the polar sky; soft ambient glow, panoramic landscape style, shifting color gradients, photographed with a DSLR camera and a wide field of view",
  "flower field in full bloom, creating a breathtaking color palette; golden hour lighting, botanical illustration style, vibrant and varied floral colors, shot with a telephoto lens",
  "classic arcade game characters, designed in a pixel art style; directional 8-bit lighting, nostalgic retro style, primary color palette, rendered with a digital art program",
  "zen garden with raked sand patterns and carefully placed stones; serene natural light, Asian-inspired style, monochrome color scheme, captured with a shallow depth of field",
  "topographical map, showcasing the beauty of Earth's diverse landscapes; sunlit aerial view, cartographic style, subtle and earthy tones, digital rendering with a 3D camera",
  "origami-inspired art, transforming paper into intricate 3D shapes; strong spotlighting, contemporary art style, pastel color palette, shot with a precisely focused camera",
  "narrow alleyway in an urban city, covered with colorful graffiti; moody and dim lighting, street art style, vivid and chaotic color mix, photographed with a high ISO setting",
  "surreal floating islands, defying gravity against a dreamy sky; ethereal backlighting, fantasy-inspired style, rich and vibrant color harmony, created with a digital painting software",
  "silhouette of a tree against a gradient sky at twilight; low-key sunset light, minimalist style, peaceful and warm color progression, captured with a vintage film camera",
  "macro shot of a frosty leaf, showcasing intricate ice patterns; dramatic side-lighting, nature-inspired style, cool and crisp blues, shot with a high-resolution macro lens",
  "watercolor splash, blending together various hues and tones; diffuse natural light, impressionistic style, harmonious color blend, photographed with a high-speed camera",
  "magnificent waterfall cascading into a serene, crystal-clear pool; bright top-down lighting, scenic landscape style, vibrant greens and blues, captured with a slow shutter speed",
  "time-lapse of busy city traffic, creating streaks of vibrant light patterns; dynamic motion blur, urban exploration style, glowing neon palette, photographed with a tripod and stable camera settings",
  "cherry blossoms in full bloom, creating a pink floral canopy; soft-filtered sunlight, romantic and dreamy style, pale pink and white tones, captured with soft focus and bokeh effects",
  "dynamic neon geometric shapes on a contrasting black background; electric backlighting, futuristic design style, bold neon color palette, rendered with a computer-generated software",
  "majestic ice cave, illuminated by ethereal, glowing light; dramatic natural reflections, otherworldly style, icy blues and purples, taken with a high dynamic range (HDR) camera setting",
  "terraced rice fields, showcasing the beauty of human-made landscapes; rich, warm sidelight, aerial photography style, lush green tones, shot with a high-altitude drone camera",
  "vintage world map, a detailed representation of global exploration; soft, even lighting, antique cartography style, faded sepia color palette, photographed with a high-resolution scanner",
  "modern architectural marvel, showcasing curves and lines in harmony; striking sunbeams, futuristic minimalist style, bold monochromatic theme, captured with geometric composition techniques",
  "line art portrait, minimalist design with striking features; simple contrasting shadows, modern art style, black and white palette, created with a digital drawing tablet",
  "long exposure photography of a meteor shower, streaks of light across the sky; natural celestial illumination, astrophotography style, deep sky blues and starry whites, taken with a sensitive camera sensor",
  "gorgeous view of rolling hills, blanketed by a sea of fog; misty, diffused light, atmospheric landscape style, soothing green and gray tones, photographed with a high-quality panoramic lens",
  "bright and energetic color gradient, transitioning seamlessly from hue to hue; smooth, radiant light, digital art style, intense and bold color spectrum, designed with a graphic software program",
  "desert landscape under a starry night sky; gentle moonlight, artistic desert composition, warm earthy hues, captured with a wide-aperture lens",
  "tropical beach scene at sunrise, with swaying palm trees and white sands; warm golden light, idyllic vacation style, vivid sky and ocean tones, captured with a high-quality wide-angle lens",
  "CYMK color explosion; spotlit complementary colors, graphic design-inspired style, bright and bold, captured with a high shutter speed",
  "modern city skyline at dusk, featuring iconic buildings and reflections; twilight glow, architectural photography style, cool blues and rich orange hues, taken with a tripod and a long exposure setting",
  "ancient abandoned temple overtaken by nature; mystical sunlight filtering through, archaeological style, muted earth tones and greens, photographed with a lead-in lines composition technique",
  "vast mountain range, with peaks that pierce the sky; high-altitude sunlight, majestic landscape style, earthy colors, captured with a wide field of view and a panoramic lens",
  "whimsical carousel, with ornate and brightly painted horses; vividly colored lighting, nostalgic amusement park style, vibrant and playful color palette, shot with a motion blur effect",
  "cosmic nebula, swirling with vivid colors and sparkling stars; soft celestial glow, immersive space art style, deep blues and vibrant colors, created with digital art software",
  "glassblowing art, with molten glass being spun and shaped; red-hot backlighting, artisan craft style, fiery oranges and reds, photographed with a short exposure time",
  "iconic movie scene, recreated with explorative composition and lighting techniques; cinematic flair, transformative film style, engaging color combinations, taken with a lens that conveys depth and emotion",
  "roaring thunderstorm, with lightning streaking across the sky; powerful contrast, dramatic weather photography style, rich blues and electric whites, captured with a long exposure setting",
  "vibrant close-up of butterfly wings; delicate, diffused light, macro nature style, vivid colors and fine details, shot with a high-resolution macro lens",
  "stylized geometric street art, using bold lines and contrasting colors; vibrant, indirect light, urban graffiti style, eye-catching color combinations, photographed with a wide-angle lens",
  "sweeping treetops, showcasing a variety of fall foliage colors; soft, even light, nature-inspired style, bright yellows, oranges, and reds, taken with a bird's-eye perspective and a drone camera",
  "re-imagined iconic painting, using digital art techniques and tools; uniform, tinted light, contemporary interpretation style, harmonious colors, created with advanced drawing software",
  "impressive cave formation, with stalactites and stalagmites; dim and mystical lighting, geological style, natural earth tones, captured with a light-sensitive camera and a wide aperture setting",
  "colorful hot air balloons, floating among the clouds; bright, sunlit sky, whimsical adventure style, festive and bright hues, taken with a high-quality zoom lens",
  "famous landmark captured from an unusual angle; dramatic shadows, architectural photography style, contrasting colors, shot with fisheye lens",
  "enchanting forest stream, with sunlight piercing the canopy; soft, dappled light, fairytale-inspired style, lush greens and earthy tones, photographed with a wide aperture and a shallow depth of field",
  "microscopic view of crystalline structure; striking backlighting, scientific imagery style, vivid and intricate color patterns, taken with a high-resolution microscopic camera",
  "bold collage of hand-written typography; varied light sources, experimental and artistic style, contrasting and harmonious colors, created with mixed media and digital manipulation",
  "steampunk-inspired cityscape, with gears, cogs, and airships; moody, industrial lighting, alternate universe style, rich bronze and metallic hues, rendered with a digital art program",
  "pop art representation of a popular cultural icon; bold and flat lighting, daring and vibrant style, bright primary colors, created with vector illustration software",
  "calm and reflective lakeside scene, with still water and a mirror-like reflection; soft, cool light, tranquil landscape style, peaceful blues and neutral tones, captured with a high-resolution camera",
  "intricate papercut art, casting shadows on a white surface; sharp, angled lighting, minimalist artistic style, monochrome color palette, photographed with accurate depth perception",
  "captivating dance performance, with graceful movements and flowing fabric; warm stage lighting, fluid motion style, passion-filled colors, taken with a fast shutter speed and accurate focus",
  "icy and frost-covered tree branches; soft, cool light, winter wonderland style, crisp whites and blues, photographed with a shallow depth of field and focus on fine details",
  "dazzling fireworks display, filling the night sky; burst of brilliant colors, celebration-inspired style, vibrant and glowing hues, captured with a long exposure setting and a wide field of view",
  "fluid acrylic art, with swirling colors and mesmerizing patterns; even, diffuse light, liquid creativity style, rich and contrasting color combinations, captured with a high-resolution camera",
  "soft-focus color gradient, transitioning smoothly between hues and shades; calming ambient light, soothing abstract style, harmonious and relaxing colors, photographed with a soft-focus lens",
  "textural surface, showcasing intricate patterns and relief; directional sidelight, unique material style, deep shadows and highlights, taken with a macro lens for high detail",
  "multiplicity of metallic shades, reflecting a complex array of colors; varying light sources, alluring metalwork style, shimmering and muted tones, captured with a high-quality lens",
  "waves of sand dunes, creating abstract lines and shapes; low and warm sunlight, nature-inspired pattern style, golden hues and earthy tones, taken with a high-resolution camera",
  "close-up detail of interlaced fabric fibers; backlit lighting, textile-focused style, soft and muted colors, shot with a high-resolution macro lens",
  "splashes of vibrant paint, blending and merging on a canvas; saturated light, expressive abstract style, bold and intense hues, captured with a fast shutter speed",
  "moire pattern, an intriguing effect created by overlapping lines and grids; well-balanced lighting, optical illusion style, hypnotic black and white, photographed with accurate focus",
  "cracked earth patterns, illustrating natural texture and variety; top-down lighting, organic surface style, desaturated earth tones, taken with a high-resolution camera",
  "holographic foil, reflecting a rainbow of iridescent colors; angled light source, futuristic material style, prismatic and shifting hues, photographed with an ultra-sharp lens",
  "abstract representation of shattered glass; strong and contrasting highlights, fragmented style, cool crisp whites and blues, captured using high-resolution techniques",
  "translucent ice crystals, revealing intricate patterns and details; backlit, cold light, frozen art style, icy blues and whites, taken with a high-resolution macro lens",
  "smooth, undulating gradient, inspired by molten lava; vibrant backlighting, intense natural phenomenon style, blazing oranges and deep blacks, created with digital art tools",
  "enlarged view of carbon fiber weave; sharp, raking light, industrial material style, monochromatic shades of gray, photographed with a high-magnification macro lens",
  "abstract bubble patterns on a dark background; reflective, directed light, ephemeral and floating style, colorful and vibrant hues, taken with a fast shutter speed",
  "impressionistic brushstrokes, forming an abstract seascape; diffused, natural light, painterly style, varied shades of blues, greens, and grays, photographed with a high-resolution camera",
  "macro shot of rusted, weathered metal; dramatic, angled lighting, rugged surface style, rich oranges and muted tones, captured with a high-resolution macro lens",
  "rippling water surface, capturing sunlight reflections; glistening natural light, aqueous abstract style, shimmering blues and greens, taken with a high-quality lens",
  "futuristic light trails, formed by fast-moving particles; dynamic streaks of color, high-speed motion style, bright neon shades on a dark background, captured with long exposure photography",
  "marbled paper, combining swirling colors and unpredictable patterns; soft, even lighting, fluid art style, rich and harmonious tones, photographed with a high-resolution camera",
  "microscopic view of intricate crystal formations; dramatic backlighting, mineralogical art style, vivid and contrasting color patterns, taken with a high-resolution microscopic lens",
  "kaleidoscopic design, showcasing stunning symmetry and colorful geometry; vibrant radial light source, mesmerizing mandala style, bright and vivid hues, created with digital manipulation",
  "highly polished chrome surface, reflecting distorted shapes and light; contrasting highlights, metallic abstraction style, cool grays and whites, captured with accurate depth perception",
  "imposing sculptural texture formed by complex geometric shapes; calculated light source, contemporary art style, monochromatic palette, photographed with a wide-angle lens",
  "colorful dust explosion, mid-air, captured with a high-speed camera; dynamically suspended particles, momentary art style, vibrantly varied hues, taken with a fast shutter speed",
  "fluorescent liquid dye patterns, activating under UV light; electric ultraviolet radiance, futuristic fluid style, glowing and vivid neon colors, captured with a specialized UV-sensitive lens",
  "fierce inferno, with dancing flames and vibrant colors; dramatic side-lighting, untamed fire style, intense reds, oranges, and yellows, photographed with a fast shutter speed",
  "fine strands of illuminated fiber optics, intertwining and glimmering; focused light, technological abstraction style, dazzling spectrum of colors, taken with a high-quality lens",
  "elaborate fractal pattern, spiraling into endless complexity; perfect symmetry, mathematical art style, vibrant and intense hues, rendered with a computer-generated algorithm",
  "glazed ceramic surface, featuring iridescent colors and reflections; diffuse light, artisan pottery style, shifting and shimmering tones, photographed with a high-resolution camera",
];
